use_frameworks!

target 'QuickLayout_Example' do
  pod 'QuickLayout', :path => '../'

  target 'QuickLayout_Tests' do
    inherit! :search_paths

  #pod 'Quick', '~> 1.2.0'
  #pod 'Nimble', '~> 7.0.2'
  end
end
