ci_service: travis_ci
coverage_service: coveralls
workspace: Example/QuickLayout.xcodeworkspace
xcodeproj: Example/QuickLayout.xcodeproj
scheme: QuickLayoutiOSDemo
source_directory: QuickLayout/
ignore:
  - cmake-debug-build/*
  - Example/*
  - Scripts/*
  - Documentaion/*
  - Tests/*
  - Pods/*
  - Applications/Xcode.app/*
  - vendor/*
  - Carthage/*
  - build/*
  - .build/*
  - .vagrant/*